### ISSUE TITLE
As far as i know, user id is random value

### ISSUE THREAD

**Issue by cozyplanes** [RazorSh4rk/DevRant-devlocation#1]

**Comment by RazorSh4rk** [comment]
I was testing the api and it seems user ids are 6 digit and rant ids are 7. I cant really think of any simpler method to fetch all of them unless theres a /users/all endpoint that i dont know about.

**Comment by cozyplanes** [comment]
It is random
There is no way to fetch them all
I remember dfox saying that they don't have a list of all rants

**Comment by cozyplanes** [comment]
And user id too

**Comment by RazorSh4rk** [comment]
I have to leave this here until we get a better way of fetching user data, until then we gotta believe in the power of normal distribution.
